name: ientity_generator
description: ientity_generator
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'


dependencies:
  build: any
  recase : any
  source_gen: any
  analyzer: any
  true_core:
    git:
      url: https://github.com/TrueCollaboration/true_core.dart.git
  ientity:
    git:
      url: https://github.com/TrueCollaboration/ientity.dart.git
  json_ex:
    git:
      url: https://github.com/TrueCollaboration/json_ex.dart.git
  json_annotation_ex:
    git:
      url: https://github.com/TrueCollaboration/json_annotation_ex.dart.git

dev_dependencies:
  build_runner: any
  build_test: any
  test: ^1.0.0
